const PAYMENT_COLORS = {
  ToPay: "#DC2626",
  Paid: "#16A34A",
  FOC: "#7C3AED",
  ToBeBilled: "#EA580C",
};

function row(label, value) {
  return `
    <tr>
      <td class="label">${label}</td>
      <td class="value">${value === "" || value === null || value === undefined ? "&mdash;" : value}</td>
    </tr>`;
}

export function buildBiltyHtml(entry) {
  const badgeColor = PAYMENT_COLORS[entry.payment_type] || "#334155";
  return `
  <!DOCTYPE html>
  <html>
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <style>
        * { box-sizing: border-box; }
        body {
          font-family: -apple-system, "Helvetica Neue", Arial, sans-serif;
          color: #0F172A;
          margin: 0;
          padding: 40px;
        }
        .sheet {
          border: 2px solid #0F172A;
          border-radius: 8px;
          overflow: hidden;
        }
        .header {
          background: #0F172A;
          color: #fff;
          padding: 24px 28px;
          display: flex;
          justify-content: space-between;
          align-items: center;
        }
        .header h1 { margin: 0; font-size: 26px; letter-spacing: 1px; }
        .header .sub { margin: 4px 0 0; font-size: 13px; opacity: 0.75; }
        .badge {
          display: inline-block;
          padding: 8px 16px;
          border-radius: 999px;
          background: ${badgeColor};
          color: #fff;
          font-weight: 700;
          font-size: 14px;
        }
        table { width: 100%; border-collapse: collapse; }
        td { padding: 14px 28px; border-bottom: 1px solid #E2E8F0; font-size: 15px; }
        td.label { width: 40%; color: #64748B; font-weight: 600; text-transform: uppercase; font-size: 12px; letter-spacing: 0.5px; }
        td.value { color: #0F172A; font-weight: 600; }
        tr:last-child td { border-bottom: none; }
        .footer { padding: 18px 28px; font-size: 12px; color: #94A3B8; text-align: center; }
      </style>
    </head>
    <body>
      <div class="sheet">
        <div class="header">
          <div>
            <h1>TRANSSOFT BILTY</h1>
            <p class="sub">Consignment Note</p>
          </div>
          <span class="badge">${entry.payment_type}</span>
        </div>
        <table>
          ${row("Consignor", entry.consignor_name)}
          ${row("Consignee", entry.consignee_name)}
          ${row("From Station", entry.from_station)}
          ${row("To Station", entry.to_station)}
          ${row("No. of Packages", entry.pkg_no)}
          ${row("Package Type", entry.pkg_type)}
          ${row("Weight (kg)", entry.weight)}
          ${row("Payment Type", entry.payment_type)}
        </table>
        <div class="footer">Generated by TransSoft Voice &bull; This is a computer-generated document.</div>
      </div>
    </body>
  </html>`;
}
